### PR TITLE
Refactor CI and add linting with flake8.

### LINKED ISSUE #27: CI is broken.
CI seems to be not working because some config is missing. 
As github actions are working very well as a CI provider for projects hosted on github (and are completely free for open source projects) I would suggest, we set it up. Also, If you agree, I would volunteer to do that. Let me know what you think.

Kind Regards

### PR DESCRIPTION
**Pull request by jakobkolb**
Follow up and fix #27 refactoring CI pipeline and add linting.

@slavaGanzin could you remove the hooks on the repo in settings (add github actions and remove circleci on PR), so the repo has nice green checkmarks again? :)

### CODE REVIEW

**Comment by slavaGanzin** [comment]
@jakobkolb 

1. Why do you need flake? As I understand black do the same
2. Why remove multiple python versions? Nose for example is not working on 3.10 and same can occur with ramda in future versions of python.
3. Webhooks removed.
4. You messed with indentation: https://github.com/slavaGanzin/ramda.py/actions/runs/1606823698/workflow#L34

**Comment by jakobkolb** [comment]
Thanks for the review!
- I'd add linting, as it checks not just code style (indentations, line breaks etc) but also pep compliance like redefinition of variables, shadowing, unused imports etc. which is nice to flag bugs before they happen.
- I left the multiple python versions in for tests because then functionality is ensured across the desired python versions but left it out for code style and linting because that should be independent of python versions.
- Fixed the workflow file, thanks for the hint!
