### ISSUE TITLE
map failed to work with 3.10

### ISSUE THREAD

**Issue by polybean** [slavaGanzin/ramda.py#29]
```py
@curry
def map(f, xs):
    if isinstance(xs, collections.Mapping):
        return dict([(k, f(v)) for k, v in xs.items()])

    return [f(x) for x in xs]
```

```
AttributeError: module 'collections' has no attribute 'Mapping'
```

**Comment by slavaGanzin** [comment]
@polybean Can you test that everything works for you now?
Update to 0.6.5
